//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Doner
    {
        public int Id { get; set; }
        [Required]
        public string Doner_name { get; set; }
        [Required]
        public string Doner_contact { get; set; }
        [Required]
        public string Doner_address { get; set; }
    }
}
